
dubbo:
  application:
    name: service-search
  registry:
    address: zookeeper://192.168.144.155:2181
  consumer:
    check: false
  protocol:
    port: -1

spring:
  data:
    solr:
      host: http://192.168.144.155:8983/solr/mycollection
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /admin
    host: 192.168.144.155
