server:
  port: 8081
spring:
  thymeleaf:
    cache: false

dubbo:
  protocol:
    port: -1
  registry:
    address: zookeeper://192.168.144.155:2181
  application:
    name: web-search
  consumer:
    check: false
