dubbo:
  application:
    name: service_goods
  registry:
    address: zookeeper://192.168.144.155:2181
  protocol:
    port: -1
  consumer:
    check: false
    retries: 0
spring:
  datasource:
    url: jdbc:mysql:///shopmall?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /admin
    host: 192.168.144.155
  redis:
    host: 192.168.144.155

mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

